#Adapted from alecjacobson/FLUFFY
#
# Try to find NANOGUI library and include path.
# Once done this will define
#
# NANOGUI_FOUND
# NANOGUI_INCLUDE_DIR
# NANOGUI_LIBRARY
#

if(NOT NANOGUI_FOUND)

FIND_PATH(NANOGUI_INCLUDE_DIR nanogui/nanogui.h)

FIND_LIBRARY( NANOGUI_LIBRARY_RELEASE NAMES nanogui)
FIND_LIBRARY( NANOGUI_LIBRARY_DEBUG NAMES nanoguid)

SET(NANOGUI_FOUND "NO")
IF (NANOGUI_INCLUDE_DIR AND NANOGUI_LIBRARY_RELEASE)
	 add_library(NanoGUI::NanoGUI STATIC IMPORTED)
	 set_property(TARGET NanoGUI::NanoGUI PROPERTY IMPORTED_LOCATION_RELEASE ${NANOGUI_LIBRARY_RELEASE})
	 if(NANOGUI_LIBRARY_DEBUG)
		set_property(TARGET NanoGUI::NanoGUI PROPERTY IMPORTED_LOCATION_DEBUG   ${NANOGUI_LIBRARY_DEBUG})
	 endif()

	SET(NANOGUI_FOUND "YES")
  SET(NANOGUI_INCLUDE_DIRS
         "${NANOGUI_INCLUDE_DIR}" "${NANOGUI_INCLUDE_DIR}/eigen3" "${NANOGUI_INCLUDE_DIR}/nanovg" CACHE STRING "" FORCE
         )
ENDIF (NANOGUI_INCLUDE_DIR AND NANOGUI_LIBRARY_RELEASE)

if(NANOGUI_FOUND)
  message(STATUS "Found NANOGUI: ${NANOGUI_INCLUDE_DIR} ${NANOGUI_LIBRARY_RELEASE}")
else(NANOGUI_FOUND)
  if (NOT NANOGUI_FIND_QUIETLY)
    message(FATAL_ERROR "could NOT find NANOGUI")
  endif (NOT NANOGUI_FIND_QUIETLY)
endif(NANOGUI_FOUND)

endif(NOT NANOGUI_FOUND)
